module.exports = {
    forms: [
        {
            startDate: new Date(2014, 2, 1),
            endDate: null,
            file: 'AL-2014.pdf',
            fields: [
                { name: 'date', required: true, type: 'date' },
                { name: 'firstName', required: true, type: 'string' },
                { name: 'middleInitial', required: true, type: 'string' },
                { name: 'lastName', required: true, type: 'string' },
                { name: 'ssn', required: true, type: 'ssn' },
                { name: 'address', required: true, type: 'string' },
                { name: 'city', required: true, type: 'string' },
                { name: 'state', required: true, type: 'string' },
                { name: 'zip', required: true, type: 'zip' },
                { name: 'line1', required: true, type: 'string' },
                { name: 'line2', required: true, type: 'string' },
                { name: 'line3', required: true, type: 'string' },
                { name: 'line4', required: true, type: 'string' },
                { name: 'line5', required: true, type: 'string' },
                { name: 'line6', required: true, type: 'string' },
                { name: 'eName', required: false, type: 'string' },
                { name: 'eIN', required: false, type: 'ein' },
                { name: 'eAddress', required: false, type: 'string' },
                { name: 'eCity', required: false, type: 'string' },
                { name: 'eState', required: false, type: 'string' },
                { name: 'eZip', required: false, type: 'zip' },
            ],
            demo: {
                firstName: 'John',
                middleInitial: 'L',
                lastName: 'Doe',
                ssn: '123-45-6789',
                address: '12345 W Some Really Long Street Address Ave.',
                city: 'Montgomery',
                state: 'AL',
                zip: '36104',
                line1: '0',
                line2: 'S',
                line3: '',
                line4: '1',
                line5: '0',
                line6: '2',
                eName: 'ABC Corp Inc.',
                eIN: '12-34567890',
                eAddress: '123 Somewhere Street',
                eCity: 'Salt Lake City',
                eState: 'UT',
                eZip: '84101',
                date: '03/28/2019'
            }
        }
    ]
};